# Generated by Django 3.2.9 on 2021-11-14 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seria', models.CharField(max_length=2, verbose_name='discount_card.seria')),
                ('number', models.PositiveIntegerField(verbose_name='discount_card.number')),
                ('release_date', models.DateTimeField(verbose_name='discount_card.release_date')),
                ('end_date', models.DateTimeField(verbose_name='discount_card.end_date')),
                ('last_use', models.DateTimeField(verbose_name='discount_card.last_use')),
                ('sum', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='discount_card.sum')),
                ('status', models.BooleanField(verbose_name='discount_card.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='discount_card.user')),
            ],
            options={
                'verbose_name': 'discount_card',
                'verbose_name_plural': 'discount_cards',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='purchase.date')),
                ('purchase_amount', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='purchase.purchase_amount')),
                ('discount_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount_cards.discountcard', verbose_name='purchase.purchase')),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
            },
        ),
    ]
